{
    "openapi": "3.0.1",
    "info": {
        "version": "2.0.2",
        "title": "Swagger test",
        "description": "Showing off swagger-ui-express",
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        }
    },
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "servers": [
        {
            "url": "https://healthy-hub-2d3x.onrender.com"
        }
    ],
    "tags": [
        {
            "name": "Auth",
            "description": "Authorization endpoints"
        },
        {
            "name": "User",
            "description": "User endpoints"
        }
    ],
    "paths": {
        "/api/auth/signup": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "User registration",
                "parameters": [],
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "requestBody": {
                    "description": "Registration's object",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/RegistrationRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/RegistrationResponse"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request (invalid request body)",
                        "content": {}
                    },
                    "409": {
                        "description": "Email in use",
                        "content": {}
                    }
                }
            }
        },
        "/api/auth/signin": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "User autorization",
                "parameters": [],
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "requestBody": {
                    "description": "Autorization's object",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/LoginRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/LoginResponse"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request (invalid request body)",
                        "content": {}
                    },
                    "401": {
                        "description": "Email or password is wrong",
                        "content": {}
                    }
                }
            }
        },
        "/api/auth/forgot-password": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "User forgot-password",
                "parameters": [],
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "requestBody": {
                    "description": "Forgot-password object",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ForgotPasswordRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "New password sent to your email",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ForgotPasswordResponse"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid email format",
                        "content": {}
                    },
                    "422": {
                        "description": "User doesn't exist!",
                        "content": {}
                    }
                }
            }
        },
        "/api/auth/signout": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "User signout",
                "parameters": [],
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "requestBody": {
                    "description": "Signout object",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Logout"
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "description": "User is logged out",
                        "content": {}
                    },
                    "401": {
                        "description": "Not authorized",
                        "content": {}
                    }
                }
            }
        },
        "/api/user/current": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Get information of current user",
                "parameters": [],
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "requestBody": {
                    "description": "User's object",
                    "content": {}
                },
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CurrentResponse"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Not authorized",
                        "content": {}
                    }
                }
            }
        },
        " /api/user/update": {
            "put": {
                "tags": [
                    "User"
                ],
                "summary": "Update user information ",
                "parameters": [],
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "requestBody": {
                    "description": "User's object",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UpdateRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UpdateResponse"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request (invalid request body)",
                        "content": {}
                    },
                    "401": {
                        "description": "Not authorized",
                        "content": {}
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "RegistrationRequest": {
                "type": "object",
                "required": [
                    "username",
                    "email",
                    "password",
                    "goal",
                    "gender",
                    "age",
                    "height",
                    "weight",
                    "activity"
                ],
                "properties": {
                    "username": {
                        "type": "string",
                        "description": "User's name",
                        "example": "Boris"
                    },
                    "email": {
                        "type": "string",
                        "description": "User's email",
                        "format": "email"
                    },
                    "password": {
                        "type": "string",
                        "description": "User's password",
                        "example": "qwerty123"
                    },
                    "goal": {
                        "type": "string",
                        "description": "User's goal",
                        "enum": [
                            "Lose Fat",
                            "Maintain",
                            "Gain Muscle"
                        ]
                    },
                    "gender": {
                        "type": "string",
                        "description": "User's goal",
                        "enum": [
                            "Male",
                            "Female"
                        ]
                    },
                    "age": {
                        "type": "integer",
                        "description": "User's age"
                    },
                    "height": {
                        "type": "integer",
                        "description": "User's height"
                    },
                    "weight": {
                        "type": "integer",
                        "description": "User's weight"
                    },
                    "activity": {
                        "type": "number",
                        "description": "User's activity",
                        "enum": [
                            "1.2",
                            "1.375",
                            "1.55",
                            "1.725",
                            "1.9"
                        ]
                    }
                }
            },
            "RegistrationResponse": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "userId": {
                            "type": "string",
                            "description": "User's id",
                            "example": "32143232436545474"
                        },
                        "email": {
                            "type": "string",
                            "description": "User's email",
                            "format": "email"
                        },
                        "username": {
                            "type": "string",
                            "description": "User's name",
                            "example": "Boris"
                        },
                        "password": {
                            "type": "string",
                            "description": "User's password",
                            "example": "$10$hkdMc.0nmSSixQvXcBYxM.3fWLh"
                        },
                        "goal": {
                            "type": "string",
                            "description": "User's goal",
                            "example": "Lose Fat"
                        },
                        "gender": {
                            "type": "string",
                            "description": "User's gender",
                            "example": "Female"
                        },
                        "age": {
                            "type": "string",
                            "description": "User's age",
                            "example": "58"
                        },
                        "height": {
                            "type": "string",
                            "description": "User's height",
                            "example": "178"
                        },
                        "weight": {
                            "type": "string",
                            "description": "User's weight",
                            "example": "132"
                        },
                        "activity": {
                            "type": "string",
                            "description": "User's activity",
                            "example": "1.2"
                        },
                        "createdAt": {
                            "type": "date",
                            "description": "User's create date",
                            "example": "2023-12-20T22:19:34.873+00:00"
                        },
                        "updatedAt": {
                            "type": "date",
                            "description": "User's update date",
                            "example": "2023-12-20T22:19:34.873+00:00"
                        },
                        "token": {
                            "type": "string",
                            "description": "JWT token",
                            "example": "null"
                        }
                    }
                },
                "example": {
                    "_id": "650b17c591f026bd77525b6d",
                    "username": "Boris",
                    "email": "test@email.com",
                    "goal": "Lose Fat",
                    "gender": "Male",
                    "age": "30",
                    "height": "180",
                    "weight": "70",
                    "activity": "1.2",
                    "createdAt": "2023-12-20T22:19:34.873+00:00",
                    "updatedAt": "2023-12-20T22:19:34.873+00:00",
                    "token": "null"
                }
            },
            "LoginRequest": {
                "type": "object",
                "required": [
                    "email",
                    "password"
                ],
                "properties": {
                    "email": {
                        "type": "string",
                        "description": "User's email",
                        "format": "email"
                    },
                    "password": {
                        "type": "string",
                        "description": "User's password",
                        "example": "qwerty123"
                    }
                }
            },
            "LoginResponse": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "userId": {
                            "type": "string",
                            "description": "User's id",
                            "example": "32143232436545474"
                        },
                        "email": {
                            "type": "string",
                            "description": "User's email",
                            "format": "email"
                        },
                        "username": {
                            "type": "string",
                            "description": "User's name",
                            "example": "Boris"
                        },
                        "password": {
                            "type": "string",
                            "description": "User's password",
                            "example": "$10$hkdMc.0nmSSixQvXcBYxM.3fWLh"
                        },
                        "goal": {
                            "type": "string",
                            "description": "User's goal",
                            "example": "Lose Fat"
                        },
                        "gender": {
                            "type": "string",
                            "description": "User's gender",
                            "example": "Female"
                        },
                        "age": {
                            "type": "integer",
                            "description": "User's age",
                            "example": "58"
                        },
                        "height": {
                            "type": "integer",
                            "description": "User's height",
                            "example": "178"
                        },
                        "weight": {
                            "type": "integer",
                            "description": "User's weight",
                            "example": "132"
                        },
                        "activity": {
                            "type": "number",
                            "description": "User's activity",
                            "example": "1.2"
                        },
                        "createdAt": {
                            "type": "date",
                            "description": "User's create date",
                            "example": "2023-12-20T22:19:34.873+00:00"
                        },
                        "updatedAt": {
                            "type": "date",
                            "description": "User's update date",
                            "example": "2023-12-20T22:19:34.873+00:00"
                        },
                        "token": {
                            "type": "string",
                            "description": "JWT token",
                            "example": "2ff5g2f5f8g5h2n1g5r5t4t85rd5gg84"
                        }
                    }
                },
                "example": {
                    "_id": "650b17c591f026bd77525b6d",
                    "username": "Boris",
                    "email": "test@email.com",
                    "goal": "Lose Fat",
                    "gender": "Male",
                    "age": "30",
                    "height": "180",
                    "weight": "70",
                    "activity": "1.2",
                    "createdAt": "2023-12-20T22:19:34.873+00:00",
                    "updatedAt": "2023-12-20T22:19:34.873+00:00",
                    "token": "fbdfbfdb45b2derbd5erbe98rb15r18erb8r"
                }
            },
            "ForgotPasswordRequest": {
                "type": "object",
                "required": [
                    "email"
                ],
                "properties": {
                    "email": {
                        "type": "string",
                        "description": "User's email",
                        "format": "email"
                    }
                }
            },
            "ForgotPasswordResponse": {
                "type": "object",
                "properties": {
                    "password": {
                        "type": "string",
                        "description": "User's password",
                        "example": "$10$hkdMc.0nmSSixQvXcBYxM.3fWLh"
                    }
                }
            },
            "Logout": {
                "type": "object",
                "required": [
                    "_id"
                ],
                "properties": {
                    "_id": {
                        "type": "string",
                        "description": "User's id"
                    }
                }
            },
            "CurrentRequest": {
                "type": "object",
                "required": [
                    "_id"
                ],
                "properties": {
                    "_id": {
                        "type": "string",
                        "description": "User's id"
                    }
                }
            },
            "CurrentResponse": {
                "type": "object",
                "properties": {
                    "username": {
                        "type": "string",
                        "description": "User's name",
                        "example": "Boris Johnson"
                    },
                    "email": {
                        "type": "string",
                        "description": "User's email",
                        "format": "email"
                    },
                    "goal": {
                        "type": "string",
                        "description": "User's goal",
                        "example": "Lose Fat"
                    },
                    "gender": {
                        "type": "string",
                        "description": "User's gender",
                        "example": "Female"
                    },
                    "age": {
                        "type": "integer",
                        "description": "User's age",
                        "example": "60"
                    },
                    "height": {
                        "type": "integer",
                        "description": "User's height",
                        "example": "170"
                    },
                    "weight": {
                        "type": "integer",
                        "description": "User's weight",
                        "example": "80"
                    },
                    "activity": {
                        "type": "number",
                        "description": "User's activity",
                        "example": "1.2"
                    },
                    "bmr": {
                        "type": "integer",
                        "description": "User's bmr",
                        "example": "560"
                    },
                    "waterRate": {
                        "type": "number",
                        "description": "User's water rate",
                        "example": "1.5"
                    },
                    "ratio": {
                        "type": "number",
                        "description": "User's ratio",
                        "example": "1.5"
                    },
                    "token": {
                        "type": "string",
                        "description": "JWT token",
                        "example": "eyJhbGcf5th4rtrthrbrrh515845cCI6IkpXVCJ9.eyJpZCI6IjY1MGIxNY5psD6fpACYwS0"
                    }
                },
                "example": {
                    "_id": "650b17c591f026bd77525b6d",
                    "name": "Boris Johnson",
                    "email": "test@email.com",
                    "goal": "Lose Fat",
                    "gender": "Male",
                    "age": "60",
                    "height": "170",
                    "weight": "80",
                    "activity": "1.2",
                    "bmr": "560",
                    "waterRate": "1.5",
                    "ratio": "1.5",
                    "token": "eyJhbGceyJpZCI6IjY13ZCIsImlhdCI6MTY5k1MzA4NTkfQ.0uWHpb4IXpsD6fpACYwS0"
                }
            },
            "UpdateRequest": {
                "type": "object",
                "required": [
                    "_id"
                ],
                "properties": {
                    "_id": {
                        "type": "string",
                        "description": "User's id"
                    }
                }
            }
        },
        "UpdateResponse": {},
        "securitySchemes": {
            "Bearer": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}